#!/usr/bin/env bash

# Set environment variables for dev
export APP_PORT=${APP_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export XDEBUG_HOST=$(ipconfig getifaddr en0) # Specific to Macintosh

COMPOSE="docker-compose"

# If we pass any arguments
if [ $# -gt 0 ];then

    # If "art" or "artisan" is used, pass-thru to "artisan"
    # inside a new container
    if [ "$1" == "art" ] || [ "$1" == "artisan" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            restapi-app \
            php artisan "$@"

    # If "composer" is used, pass-thru to "composer"
    # inside a new container
    elif [ "$1" == "composer" ];then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            restapi-app \
            composer "$@"

    # If "test" is used, run unit tests,
    # pass-thru any extra arguments to php-unit
    elif [ "$1" == "test" ];then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            restapi-app \
            ./vendor/bin/phpunit "$@"
    else
        $COMPOSE "$@"
    fi
else
   $COMPOSE ps
fi